// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  GetApiResourceData,
  PostApiResourceData,
  PutApiResourceData,
  GetApiResourceStatesData,
  GetApiResourceTypesData,
  GetApiResourceTypesResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export const getApiResource = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiResourceData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: "/api/Resource",
    ...options,
  });
};

export const postApiResource = <ThrowOnError extends boolean = false>(
  options?: Options<PostApiResourceData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
    url: "/api/Resource",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const putApiResource = <ThrowOnError extends boolean = false>(
  options?: Options<PutApiResourceData, ThrowOnError>,
) => {
  return (options?.client ?? client).put<unknown, unknown, ThrowOnError>({
    url: "/api/Resource",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const getApiResourceStates = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiResourceStatesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: "/Api/ResourceStates",
    ...options,
  });
};

export const getApiResourceTypes = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiResourceTypesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApiResourceTypesResponse,
    unknown,
    ThrowOnError
  >({
    url: "/api/ResourceTypes",
    ...options,
  });
};
