// This file is auto-generated by @hey-api/openapi-ts

export type ResourceCreateDto = {
  name?: string | null;
  description?: string | null;
  image?: string | null;
  resourceTypesId?: number;
};

export type ResourceTypesDto = {
  id?: number;
  name?: string | null;
};

export type ResourceUpdateDto = {
  name?: string | null;
  description?: string | null;
  id?: number;
};

export type GetApiResourceData = {
  body?: never;
  path?: never;
  query?: {
    resourceTypeId?: number;
  };
  url: "/api/Resource";
};

export type GetApiResourceResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiResourceData = {
  body?: ResourceCreateDto;
  path?: never;
  query?: never;
  url: "/api/Resource";
};

export type PostApiResourceResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiResourceData = {
  body?: ResourceUpdateDto;
  path?: never;
  query?: never;
  url: "/api/Resource";
};

export type PutApiResourceResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiResourceStatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/Api/ResourceStates";
};

export type GetApiResourceStatesResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiResourceTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/ResourceTypes";
};

export type GetApiResourceTypesResponses = {
  /**
   * OK
   */
  200: Array<ResourceTypesDto>;
};

export type GetApiResourceTypesResponse =
  GetApiResourceTypesResponses[keyof GetApiResourceTypesResponses];
